services:
  postgres:
    build: ./backend/app/postgres
    ports:
      - 5432
  back:
    build:
      context: backend
    volumes:
      - "./backend/app:/usr/src/app"
    restart: unless-stopped
    ports:
      - 5000
    depends_on:
      - postgres
  # front:
  #   build:
  #     context: frontend
  #   restart: unless-stopped
  #   ports:
  #     - 3000
  #   volumes:
  #     - ./frontend/app:/app:z
  # nginx:
  #   image: nginx:1.25.4-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - back
  #     # - front
  #   ports:
  #     - "80:80"
