services:
  postgres:
    build: ./backend/app/postgres
    ports:
      - 1488:5432
  back:
    build:
      context: backend
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/web:/usr/share/nginx/html
    ports:
      - "80:80"

